NUM_GPUS: 4

TRAIN:
  MODEL: "anynet"
  IM_SIZE: 224
  BATCH_SIZE: 32

#--------------------------------
DATASET:
  PATH: '/home/yodchanan/dream/datasets/tuberculosis_xray'
  NAME: 'tb'
  SHUFFLE: true
  N_CLASSES: 2


#--------------------------------
  

OPTIM:
    BASE_LR: 0.01
    LR_POLICY: cos
    MAX_EPOCH: 20
    BURNIN: 0
    WARMUP_FACTOR: 0.1
    
    SGD:
        MOMENTUM: 0.9
        NESTEROV: true
        DAMPENING: 0.0
        WEIGHT_DECAY: 0.0001


#--------------------------------

WANDB:
  PROJECT: 'default_project'
  NAME: 'default_name'

#--------------------------------

MEM:
  RELU_INPLACE: true

BN:
  EPS: 0.00001
  MOMENTUM: 0.1

#==============  MODEL ===============

ANYNET:
  STEM_OUT: 6
  STAGE_LIMIT_MIN: 2
  STAGE_LIMIT_MAX: 6
  DEPTH_LIMIT: 16
  WIDTH_LIMIT: 128
  B_RATIO_LIMIT: [1,2,4]
  BIAS: false

#=====================================
RANDOM_SEED: 1
